### PR TITLE
Bulk delete computers and packages

### PR DESCRIPTION
**Pull request by sloanelybutsurely**
Computers are deleted asynchronously but package deletes are still synchronous.

/cc @rickychilcott

### CODE REVIEW

**Comment by sloanelybutsurely** [comment]
Ah... Tests are failing because we no longer support ruby 1.9.3 by adding Sidekiq...

**Comment by rickychilcott** [comment]
Hey Zach. This is great... but, we should do a few things.

1) Add tests for the worker individually, and to make sure that a worker is queued when you set it to delete
2) Have a worker get queued when you delete a single computer
3) Add a flash message to let people know what's going on

**Comment by rickychilcott** [comment]
We should also add some docs in the wiki about this

**Comment by sloanelybutsurely** [comment]
This has been updated. Want to take another look, @rickychilcott ?

**Comment by rickychilcott** [comment]
Is this truly ready to merge? Your testing issues were on a different PR or were they related to this one?

Let me know. Thanks @zperrault

**Comment by sloanelybutsurely** [comment]
Those testing issues are on this PR, I have not pushed those changes.

**Comment by sloanelybutsurely** [comment]
I think this should be good! Can you take another look, @rickychilcott ?

**Pull request merged**
