### PR TITLE
Some improvements to the shared package list

### PR DESCRIPTION
**Pull request by sloanelybutsurely**
This adds pagination and proper version sorting to the shared packages listing.

/cc @rickychilcott

### CODE REVIEW

**Comment by rickychilcott** [comment]
We've got some failing tests. Thoughts about those?

**Comment by rickychilcott** [comment]
Functionality seems awesome. Can't wait to put into production

**Comment by sloanelybutsurely** [comment]
Pretty sure the failing tests are just not having merged master... I'll give that a shot.

**Comment by rickychilcott** [comment]
Tests passing. Merge!

**Pull request merged**
